# Generated by Django 4.2.1 on 2023-05-13 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_thingspeaks_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
