# Generated by Django 4.2.1 on 2023-05-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_measurementtypes_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementtypes',
            name='unit',
        ),
    ]
