# Generated by Django 4.2.1 on 2023-05-13 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_measurementtypes_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='thingspeak',
        ),
        migrations.AddField(
            model_name='measurementtypes',
            name='thingspeak',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thingspeak_server', to='app.thingspeaks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
